package day42_Exceptions_Continue;

public class ThrowsKeyword2 {


    public static void main(String[] args) {


        System.out.println("Test started");

        System.out.println(8/0);

        System.out.println("Test completed");






    }





}
